### ISSUE TITLE
Twitch player in Markdown posts does not render with default config

### ISSUE THREAD

**Issue by davidwesst** [davidwesst/davidwesst.github.io#86]
See https://www.davidwesst.com/blog/missing-bootloader-in-vscode-devcontainer/ for example.

The Twitch player needs to have a few attributes added each time it is used. Investigate and potentially implement a "player component" that can be used in Markdown posts to reference Twitch videos or clips.

Documentation: https://dev.twitch.tv/docs/embed

**Comment by davidwesst** [comment]
Not applicate with `v9` relaunch.

**Comment by SchoolUnblockers22** [comment]
Can you help me get around iframes?
